name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: wasm-pack-action
      uses: jetli/wasm-pack-action@v0.3.0
    - name: Build
      run: wasm-pack build --release --target web
    - name: Run tests
      run: cargo test --verbose
    - name: Deploy
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{ secrets.SSH_KEY }}
      with:
        flags: '-avzr --delete'
        options: ''
        ssh_options: '-p 2222'
        src: 'pkg/'
        dest: 'katsu@katsyoshi.org:src/webpage/pkg/'
