name: Rust

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: wasm-pack-action
      uses: jetli/wasm-pack-action@v0.3.0
    - name: Build
      run: wasm-pack build --release --target web
    - name: Run tests
      run: cargo test --verbose
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        path: ${{ secrets.DEPLOY_PATH }}
        remote_path: ${{ secrets.DEPLOY_DEST }}
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_port: ${{ secrets.DEPLOY_PORT }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
